### ISSUE TITLE
make personal website

### ISSUE THREAD

**Issue by arpit1997** [arpit1997/arpit1997.github.io#1]

**Comment by HackersSpirit** [comment]
@arpit1997 : Do you want me to help

**Comment by arpit1997** [comment]
yeah sure. try if you can complete this

**Comment by HackersSpirit** [comment]
@arpit1997 : Sure will try to help just tell me how you want it.

**Comment by sounak98** [comment]
If you want me to, I can make a good website for you. :)

**Comment by arpit1997** [comment]
Thanks for your contributions @KamalAwasthi
